name: PR Security Review

permissions:
  pull-requests: write  # Needed for leaving PR comments
  contents: read

on:
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 2
      
      - uses: anthropics/claude-code-security-review@main
        with:
          comment-pr: true
          run-every-commit: true
          claude-api-key: ${{ secrets.CLAUDE_API_KEY }}
      
      - name: Fail if findings exist
        run: |
          if [ -f "claude-findings.json" ] && [ "$(jq '.findings | length' claude-findings.json)" -gt 0 ]; then
            echo "Security issues detected by Claude."
            exit 1
          else
            echo "No security issues detected."
          fi